import numpy as np
import time
from datetime import datetime


class Individual:
    """
    A class representing an individual in an evolutionary algorithm.

    Attributes:
    - search_variables (np.array): The search variables of the individual.
    - strategy_parameters (np.array): The strategy parameters of the individual.
    - fitness (float): The fitness of the individual.
    - created_at (datetime): The timestamp of the individual's creation.
    """

    def __init__(self, search_variables = None, strategy_parameters =  None, fitness = None) -> None:
        self.search_variables = search_variables
        self.strategy_parameters = strategy_parameters
        self.fitness = fitness
        self.created_at = datetime.fromtimestamp(time.time())

    def as_bitstring(self):
        """
        Convert the individual to a bit string representation.

        Returns:
        - List[int]: The bit string representation of the individual.
        """
        return [1 if sv >= 0 else 0 for sv in self.search_variables]

    def set_fitness(self, fitness: float):
        """
        Set the individual's fitness.

        Args:
        - fitness (float): The fitness value to set.
        """
        self.fitness = fitness

    def evaluate(self, problem) -> float:
        """
        Evaluate the individual's fitness based on a given problem.

        Args:
        problem (Callable): The problem to be evaluated.

        Returns:
        float: The fitness of the individual.
        """
        return problem(self.as_bitstring())

    def discrete_recombination(self, individual, probability: float = 0.5, random_state = None):
        """
        Perform discrete recombination (uniform crossover) with another individual.

        Args:
        - individual (Individual): The individual to crossover with.
        - probability (float): The crossover probability.
        - random_state (int): Seed for the random number generator. Defaults to None.

        Returns:
        - Individual: The resulting individual from the crossover.
        """
        rs = np.random.RandomState(
            random_state) if random_state is not None else np.random
        recombination = Individual()
        recombination.search_variables = [sv1 if rs.rand() >= probability else sv2 for sv1,
                                          sv2 in zip(self.search_variables, individual.search_variables)]

        recombination.strategy_parameters = [sp1 if rs.rand() >= probability else sp2 for sp1,
                                             sp2 in zip(self.strategy_parameters, individual.strategy_parameters)]
        return recombination

    def intermediate_recombination(self, individual):
        """
        Perform intermediate recombination with another individual to generate a new individual.

        Args:
        - individual (Individual): The individual to recombine with.

        Returns:
        - Individual: A new individual generated by intermediate recombination.
        """
        recombination = Individual()
        recombination.search_variables = [
            (sv1 + sv2)/2 for sv1, sv2 in zip(self.search_variables, individual.search_variables)]
        recombination.strategy_parameters = [
            (sp1 + sp2)/2 for sp1, sp2 in zip(self.strategy_parameters, individual.strategy_parameters)]
        return recombination

    def mutate(self, random_state: int = None):
        """
        Perform mutation on the individual.

        Args:
        - random_state (int): Seed for the random number generator. Defaults to None.

        Returns:
        - Individual: The mutated individual.
        """
        rs = np.random.RandomState(
            random_state) if random_state is not None else np.random
        n = len(self.search_variables)

        # Learning rates
        lr_global = 1 / np.sqrt(2 * n)  # t'
        lr_local = 1 / np.sqrt(2 * np.sqrt(n))  # t

        # Sample a global perturbation
        g = rs.normal(0, 1)

        # Mutate individual step sizes
        sigma_prime = [
            sig * np.exp(lr_global * g + lr_local * rs.normal(0, 1)) for sig in self.strategy_parameters]

        # Mutate search variables
        x_prime = [xi + sigpi * rs.normal(0, 1)
                   for xi, sigpi in zip(self.search_variables, sigma_prime)]

        return Individual(x_prime, sigma_prime)

    @classmethod
    def random(cls, dimension: int, problem, random_state = None):
        """
        Create a random individual.

        Args:
        - dimension (int): The dimensionality of the individual.
        - problem (function): The optimization problem function. 
        - random_state (int): Seed for the random number generator. Defaults to None.

        Returns:
        - Individual: A new random individual.
        """
        rs = np.random.RandomState(
            random_state) if random_state is not None else np.random
        x = rs.uniform(-1, 1, size=dimension)
        sigma = rs.uniform(0.1, 1, size=dimension)

        individual = cls(x, sigma)

        fitness = problem(individual.as_bitstring())
        individual.set_fitness(fitness)
        return individual

    def __str__(self) -> str:
        return f'Score({id(self)}) = {self.fitness}'
