from .individual import Individual
import numpy as np


class Population:
    """
    A class representing a population of individuals in an evolutionary algorithm.

    Attributes:
    - population (List[Individual]): The population of individuals.
    """

    def __init__(self, population = []) -> None:
        self.population = population

    def add(self, individual: Individual):
        self.population.append(individual)

    @classmethod
    def new(cls, mu: int, dimension: int, problem):
        """
        Create a new population with mu individuals.

        Args:
        - mu (int): The number of individuals in the population.
        - dimension (int): The dimensionality of the problem.
        - problem : The optimization problem.

        Returns:
        - Population: A new population of mu individuals.
        """
        pop = [Individual.random(dimension, problem) for _ in range(mu)]
        return cls(pop)

    def roulette_selection(self, random_state = None) -> Individual:
        """
        Select an individual from the population using roulette wheel selection.

        Args:
        - random_state (int): Seed for the random number generator. Defaults to None.

        Returns:
        - Individual: The selected individual.
        """
        rs = np.random.RandomState(
            random_state) if random_state is not None else np.random
        fitness = self.fitness()
        total_fitness = sum(fitness)
        selection_point = rs.uniform(0, total_fitness)

        cumulative_fitness = 0
        selected_index = 0

        for i, fitness in enumerate(fitness):
            cumulative_fitness += fitness
            if cumulative_fitness >= selection_point:
                selected_index = i
                break

        return self.population[selected_index]

    def k_tournament_selection(self, k: int, random_state = None) :
        """
        Select parents using k-tournament selection.

        Args:
        - k (int): The tournament size.
        - random_state (int): Seed for the random number generator. Defaults to None.

        Returns:
        - List[Individual]: The selected parents.
        """
        rs = np.random.RandomState(
            random_state) if random_state is not None else np.random
        selected_parents = []
        tournament_size = k
        population_size = len(self.population)

        for _ in range(tournament_size):
            tournament_indices = rs.choice(
                population_size, size=k, replace=False)
            tournament = [self.population[i] for i in tournament_indices]
            tournament_fitness = [ind.fitness for ind in tournament]
            best_individual = tournament[np.argmax(tournament_fitness)]
            selected_parents.append(best_individual)

        return selected_parents

    def random_selection(self, random_state: int = None) -> Individual:
        """
        Selects a random individual from the population.

        This function selects a random individual from the population stored in the object.

        Args:
        - random_state (int): Seed for the random number generator. Defaults to None.

        Returns:
        - Individual: The randomly selected individual.
        """
        rs = np.random.RandomState(
            random_state) if random_state is not None else np.random
        population_size = len(self.population)
        return self.population[rs.randint(0, population_size)]

    def global_discrete_recombination(self, random_state: int = None) -> Individual:
        """
        Perform global discrete recombination to generate a new individual.

        Args:
        - random_state (int): Seed for the random number generator. Defaults to None.

        Returns:
        - Individual: A new individual generated by global discrete recombination.
        """
        rs = np.random.RandomState(
            random_state) if random_state is not None else np.random
        num_parents = len(self.population)
        num_variables = len(self.population[0].search_variables)

        recombination = Individual()

        recombination.search_variables = [self.population[rs.randint(
            num_parents)].search_variables[i] for i in range(num_variables)]
        recombination.strategy_parameters = [self.population[rs.randint(
            num_parents)].strategy_parameters[i] for i in range(num_variables)]

        return recombination

    def global_intermediate_recombination(self) -> Individual:
        """
        Perform global intermediate recombination to generate a new individual.

        Returns:
        - Individual: A new individual generated by global intermediate recombination.
        """
        num_parents = len(self.population)
        num_variables = len(self.population[0].search_variables)

        recombination = Individual()

        recombination.search_variables = [sum(
            [ind.search_variables[i] for ind in self.population]) / num_parents for i in range(num_variables)]
        recombination.strategy_parameters = [sum(
            [ind.strategy_parameters[i] for ind in self.population]) / num_parents for i in range(num_variables)]

        return recombination

    def sorted(self, reversed: bool = True, key=None):
        """
        Sort the population based on fitness.

        Args:
        - reversed (bool): Whether to sort in descending order (default True).
        - key (function): The key function to use for sorting (default None).

        Returns:
        - Population: The sorted population.
        """
        key = key if key is not None else lambda x: x.fitness
        self.population.sort(key=key, reverse=reversed)
        return self

    def elitist_selection(self, mu: int):
        """
        Select the top mu individuals based on their fitness.

        Args:
        - mu (int): The number of individuals to select.

        Returns:
        - Population: The top mu individuals selected from the offspring population.
        """
        return Population(self.sorted().population[:mu])

    def mating_selection(self, population, mu: int):
        """
        Selects the best individuals from the combined population to become parents for the next generation.

        This function combines the population stored in the object with another population and selects the best individuals
        from the combined population to become parents for the next generation.

        Parameters:
        - population: another population to combine with the object's population
        - mu: the number of individuals to select as parents

        Returns:
        - Self: A new population object containing the selected parents.
        """
        return Population(sorted(self.population + population.population, reverse=True, key=lambda x: x.fitness)[:mu])

    def fitness(self):
        """
        Calculate the fitness of the population.

        Returns:
        - List[float]: The fitness values of the individuals in the population.
        """
        return [i.fitness for i in self.population]

    def fittest(self) -> Individual:
        """
        Return the fittest individual in the population.

        Returns:
        - Individual: The fittest individual in the population.
        """
        return self.sorted().population[0]

    def clear(self):
        """
        Clear the population data.

        This function clears the population data stored in the object.

        Returns:
        - None
        """
        self.population.clear()
